services:
  directory-service:
    container_name: directory-service
    build:
        context: .
        dockerfile: ./backend/DirectoryService/DirectoryService.Web/Dockerfile
    ports:
      - "9002:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ASPNETCORE_URLS=http://+:8080"
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=directory_service;Username=postgresUser;Password=postgresPassword
      - Serilog__WriteTo__1__Args__serverUrl=http://seq:5341- 
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
    restart: always

  seq:
    container_name: directory-service-seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "15341:5341" 
      - "8081:80"
    restart: always  

  postgres: 
    container_name: directory-service-postgres
    image: postgres:15
    environment: 
      POSTGRES_DB: directory_service
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresUser -d directory_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:     



  
 